### ISSUE TITLE
Update schedule

### ISSUE THREAD

**Issue by bradleyboehmke** [uc-python/advanced-python-datasci#30] opened 2021-12-23 17:47 UTC
Once all the sections are completed we should update the schedule to accurately reflect the module names. We can also revise rough timeline as well if we think that has changed.

**Comment by eswan18** [comment] 2022-01-03 03:49
Here's a quick-and-dirty draft of the times for my sections. I'm trying to learn from experience and mentally add some extra time to my estimates since I know I always run long.

| Section | Estimated Time |
| -- | -- |
| Setting the Stage | minimum 15 (however long we want it to be) |
| Git | 45 |
| EDA | |
| First Model | |
| Modularity Part 1 | 60 |
| Feature Engineering | |
| Model Evaluation | |
| Modularity Part 2 | 60 |
| Testing | 60 |
| ML Lifecycle | |

That's 4 hours total. If we teach 9-12 each day and assume 3ish of those hours for the case study, there's room for 9 hours of instruction and my sections are at about half of that time.

**Comment by bradleyboehmke** [comment] 2022-01-05 23:59
So are you not planning on doing the [Reproducibility with dependency tracking](https://github.com/uc-python/advanced-python-datasci/blob/develop/README.md#tentative-agenda) section?  Is Testing taking the place of that session?

**Comment by bradleyboehmke** [comment] 2022-01-06 00:04
Also, most sections are quite obvious regarding which of us is speaking.  However, how do we want to split up the Introduction and Setting the Stage sections?  I do the Intro and you do the other or vice versa?  Any preference?

**Comment by eswan18** [comment] 2022-01-06 02:21
> So are you not planning on doing the [Reproducibility with dependency tracking](https://github.com/uc-python/advanced-python-datasci/blob/develop/README.md#tentative-agenda) section? Is Testing taking the place of that session?

I think the Reproducibility section would be my first choice to cut if we won't have enough time. Based on my estimate above, I'm going to guess that we won't. That said, if we update the timings and decide we *do* have time for it, I'm still happy to add it.

> Also, most sections are quite obvious regarding which of us is speaking. However, how do we want to split up the Introduction and Setting the Stage sections? I do the Intro and you do the other or vice versa? Any preference?

I'm happy to do whatever. The most sensible arrangement probably depends upon whether we end up including Setting the Stage or just using your EDA section as that intro. If we do StS, I'll cover it, since I think I originally made that material – and you could do the intro. If we don't, that probably adds some time to your EDA section, so I could do the intro.

**Comment by eswan18** [comment] 2022-01-07 22:20
After finishing the testing section, I think it'll take a little longer than I'd anticipated. I also thought more about Modularity part 2 and updated timings for that. My total time is still 3:45 (not including Setting the Stage).

| Section | Estimated Time |
| -- | -- |
| Setting the Stage | minimum 15 (however long we want it to be) |
| Git | 45 |
| EDA | 30-45 |
| First Model | 45 |
| Modularity Part 1 | 60 |
| Feature Engineering | 60 |
| Model Evaluation | 75 |
| Modularity Part 2 | 45 |
| Testing | 75 |
| ML Lifecycle | 60 |

@bradleyboehmke Do you want to fill in timings for your sections and we can figure out how to update the schedule?

**Comment by bradleyboehmke** [comment] 2022-01-08 19:36
@eswan18 , I updated the timings in the previous comment. My timings match the schedule on the current [README](https://github.com/uc-python/advanced-python-datasci#tentative-agenda) and in the [Intro section](https://github.com/uc-python/advanced-python-datasci/blob/master/notebooks/00-Introduction.ipynb).

We just need to think about how to adjust the agenda for modularity 2 and testing.  Looks like we will have more time available on Day 3 but less time on Day 4.  Maybe we could let them work on the case study a little bit on both days?  Or do we spend the extra time on Day 3 reviewing part 1 of the case study?

**Comment by eswan18** [comment] 2022-01-09 23:06
I figured it would be easier to just split some of the Testing section over both days. Here's an adjustment to the schedule that reconciles everything, I believe. 

| Day | Topic                                                                          |     Time      |
| :-: | :----------------------------------------------------------------------------- | :-----------: |
|  1  | Introductions                                                                  |  9:00 - 9:15  |
|     | Setting the Stage                                                              |  9:15 - 9:30  |
|     | Git & version control                                                          |  9:30 - 10:15 |
|     | Break                                                                          | 10:15 - 10:30 |
|     | EDA & Our first Scikit-learn model                                              | 10:30 - 12:00 |
|     | Q&A                                                                            | 12:00 - 12:30 |
|  2  | Q&A                                                                            |  8:30 - 9:00  |
|     | Modular code                                                                   |  9:00 - 10:00 |
|     | Feature engineering                                                            | 10:00 - 11:00 |
|     | Break                                                                          | 11:00 - 11:15 |
|     | Case Study, pt. 1                                                              | 11:15 - 12:00 |
|     | Q&A                                                                            | 12:00 - 12:30 |
|  3  | Q&A                                                                            |  8:30 - 9:00  |
|     | Model evaluation & selection                                                   |  9:00 - 10:15 |
|     | Break                                                                          | 10:15 - 10:30 |
|     | More on modular code                                                      | 10:30 - 11:15 |
|     | Unit tests                                                      | 11:15 - 12:00 |
|     | Q&A                                                                            | 12:00 - 12:30 |
|  4  | Q&A                                                                            |  8:30 - 9:00  |
|     | More on unit tests                                                  | 9 - 9:30 |
|     | ML lifecycle management                                                        |  9:30 - 10:30 |
|     | Break                                                                          | 10:30 - 10:45 |
|     | Case Study, pt. 2                                                              | 10:45 - 11:45 |
|     | Case Study Review, pt. 2 and Q&A                                               | 11:45 - 12:30 |

Let me know if this looks okay to you, and if so, I'll update the schedule in the readme and intro.

**Comment by bradleyboehmke** [comment] 2022-01-10 02:01
Yep, looks good to me.

**Comment by eswan18** [comment] 2022-01-10 12:51
Closed in #49

**Closed as completed by eswan18** 2022-01-10 12:51 UTC
